modLoader = "javafml"
loaderVersion = "[${forgeMinVersion},)"
issueTrackerURL = "https://github.com/${githubUser}/${githubRepo}/issues"
license = "${license}"
logoFile = "logo.png"

[[mods]]
modId = "${modId}"
version = "${version}"
displayName = "${modName}"
authors = "${modAuthor}"
description = '''${modDescription}'''

[[dependencies.${modId}]]
modId = "forge"
mandatory = true
versionRange = "[${forgeMinVersion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${modId}]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,1.20)"
ordering = "NONE"
side = "BOTH"
